import type {Metadata} from "next";
import { Limelight } from "next/font/google";
import { Finlandica } from "next/font/google";
import "./globals.css";

const limelight = Limelight({
    variable: "--font-limelight",
    weight: '400',
    subsets: ['latin'],
})

const finlandica = Finlandica({
    variable: "--font-finlandica",
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${limelight.variable} ${finlandica.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
